FEC-11614 - Pass the program ID when sending a bookmark
kaltura/playkit-ios-providers pull request #52
Opened 2021-10-13 15:08 UTC by giladna

this epgId will be used in bookmark requests

Solves FEC-11614

2021-10-26 12:09 UTC, x-NR-x requested changes

2021-10-26 12:09 UTC, x-NR-x commented on Sources/OTT/Provider/PhoenixMediaProvider.swift
> +        }
Please remove line 655 it is not needed because it is done on line 659.
OTTRecordingAsset inherits from OTTProgramAsset, and 'epgId' is a property of OTTProgramAsset.
There is no "if else", therefor it will enter Line 658 for both objects.

2021-10-26 12:09 UTC, x-NR-x commented on Sources/OTT/Provider/PhoenixMediaProvider.swift
>          }
```suggestion
        // Prefer epgId if given by app
        if let epgId = loaderInfo.epgId {
            metadata["epgId"] = epgId
        }
```

2021-10-28 13:10 UTC, giladna commented on Sources/OTT/Provider/PhoenixMediaProvider.swift
> +        }
done

2021-10-31 07:37 UTC, x-NR-x requested changes
Sorry I didn't see this previously.

2021-10-31 07:37 UTC, x-NR-x commented on Sources/OTT/Services/BookmarkService.swift
> +        }
The comment is not needed, it is understood from the if statement.
```suggestion
        if let epgId = epgId {
            json["programId"] = JSON(epgId)
        }
```

2021-10-31 07:38 UTC, x-NR-x approved these changes

2021-10-31 07:43 UTC, merged