FEC-10931 Add support for KalturaPlaybackCaption in OVP providers
kaltura/playkit-ios-providers pull request #61
Opened 2022-04-25 07:48 UTC by chausov

Solves FEC-10931
Add support for KalturaPlaybackCaption in OVP providers

2022-05-03 12:33 UTC, chausov commented
Add boolean useApiCaptions by default false.

2022-05-03 14:03 UTC, x-NR-x approved these changes
Just cleanup unneeded commented code.

2022-05-03 14:03 UTC, x-NR-x commented on Sources/OVP/Provider/OVPMediaProvider.swift
> +                // if let flavors = mediaSources.flavors, flavors.isEmpty {
If this is not needed please clean.

2022-05-03 16:20 UTC, x-NR-x requested changes
Missing _'useApiCaptions'_ to enable/disable the feature.

2022-05-24 13:22 UTC, x-NR-x approved these changes

2022-05-25 22:17 UTC, merged